#### OBJECTIVE
supprimmer toutes les donnés confidentielles
Fusionner tout dans un seule et meme data frame :

In [2]:
import pandas as pd 

events = pd.read_csv("/home/prime/Projets/2026_PROJECT-DA/DATA/events.csv")
pax = pd.read_csv("/home/prime/Projets/2026_PROJECT-DA/DATA/pax.csv")

#### INFORMATIONS
Comprendre ce que contiennent les DataFrame :

In [3]:
print("EVENTS", events.columns)
display(events.head(3))

print("PAX",pax.columns)
pax.head(3)

EVENTS Index(['Unnamed: 0', 'Code', 'Matricule', 'Nom', 'Prénom', 'Téléphone',
       'Qualification', 'Equipe', 'Heure de convocation', 'Blacklist',
       'Passage exterieur', 'Passage accred', 'Passage vestiaire',
       'Prise de poste', 'Fin de poste', 'Temps travaillé',
       'Lieu de prise de poste', 'Lieu de fin de poste', 'Event'],
      dtype='object')

,Unnamed: 0,Code,Matricule,Nom,Prénom,Téléphone,Qualification,Equipe,Heure de convocation,Blacklist,Passage exterieur,Passage accred,Passage vestiaire,Prise de poste,Fin de poste,Temps travaillé,Lieu de prise de poste,Lieu de fin de poste,Event
0,0,82929|a539fb6bb248d168,38859,CISSE,Oumar,33638033860,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 11:59:26,0,28-07-2024 12:17:46,28-07-2024 14:32:55,28-07-2024 22:37:41,07:34:46,B605,B605,2024-07-28_JO_Rugby-F.xlsx
1,1,83104|1e35386face21ade,38903,HOU,Jerome Wei,33783012177,MANAGER POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 11:04:21,0,28-07-2024 11:22:02,28-07-2024 11:36:04,0,0,LOGE 1,NaN,2024-07-28_JO_Rugby-F.xlsx
2,2,84591|d2e6d7cde2df98b8,39423,DRAME,Sokhna,33635502833,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 10:43:26,0,28-07-2024 10:54:53,0,0,0,NaN,NaN,2024-07-28_JO_Rugby-F.xlsx

PAX Index(['Unnamed: 0', 'Matricule', 'Civilité', 'Nom', 'Prénom', 'Adresse 1',
       'Code postal', 'Ville', 'Pays', 'Téléphone mobile', 'Email',
       'Date naissance', 'Pays de naissance', 'Nationalité', 'Qualifications',
       'Création', 'Formation Stade Prépa BOU', 'Formation Stade Manager BOU',
       'HACCP BOU', 'Langue BOU', 'Visite Médicale BOU'],
      dtype='object')

,Unnamed: 0,Matricule,Civilité,Nom,Prénom,Adresse 1,Code postal,Ville,Pays,Téléphone mobile,...,Date naissance,Pays de naissance,Nationalité,Qualifications,Création,Formation Stade Prépa BOU,Formation Stade Manager BOU,HACCP BOU,Langue BOU,Visite Médicale BOU
0,1,31246,Madame,AABBOUB,Nisrine,10 Rue JULES VERNE,91300,MASSY,France,+33659503167,...,1980-08-12,Maroc,Maroc,"PLONGEUR, CONSULTATION BOULOGNE, CONSULTATION ...",2020-09-04 14:45:25,NaN,NaN,Oui,NaN,Oui
1,2,42600,Madame,AABOUDA,Basma,1 Rue BENJAMIN DELESSERT,93500,PANTIN,France,+33665716925,...,2002-07-14,France,France,"CONSULTATION BOULOGNE, AGENT DE RESTAURATION",2024-04-22 14:45:11,NaN,NaN,NaN,NaN,NaN
2,3,36320,Madame,AADAL,Malika,6 Square ROGER MARTIN DU GARD,92390,VILLENEUVE LA GARENNE,France,+33 7 53 35 36 80,...,2004-03-19,France,France,"GUEST CONTROL, HOTE D ATTRACTION, COMMIS DE CU...",2022-11-20 02:45:01,NaN,Oui,Oui,NaN,Oui

#### FUSION
Fusionner les DataFrame dans un nouveaux
On vas certainemetn garder l'ensemble des evenement et fuisionner les pax dessus

In [4]:
dataset = events.merge(pax, on="Matricule", how="left")
dataset = events.merge(pax, on="Matricule", how="inner")
dataset.head()

,Unnamed: 0_x,Code,Matricule,Nom_x,Prénom_x,Téléphone,Qualification,Equipe,Heure de convocation,Blacklist,...,Date naissance,Pays de naissance,Nationalité,Qualifications,Création,Formation Stade Prépa BOU,Formation Stade Manager BOU,HACCP BOU,Langue BOU,Visite Médicale BOU
0,0,82929|a539fb6bb248d168,38859,CISSE,Oumar,33638033860,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2004-12-20,Sénégal,France,"CONSULTATION BOULOGNE, COMMIS DE CUISINE, AGEN...",2023-07-19 02:45:13,Oui,NaN,Oui,NaN,NaN
1,1,83104|1e35386face21ade,38903,HOU,Jerome Wei,33783012177,MANAGER POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2003-09-13,France,France,"CONSULTATION BOULOGNE, MANAGER POINT DE VENTE,...",2023-07-21 02:45:12,NaN,Oui,Oui,NaN,Oui
2,2,84591|d2e6d7cde2df98b8,39423,DRAME,Sokhna,33635502833,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2002-06-29,France,France,"CONSULTATION BOULOGNE, COMMIS DE CUISINE, HOTE...",2023-08-30 02:45:16,Oui,NaN,Oui,NaN,Non
3,3,93097|f39f9bcc50a3ff7f,42702,HALL,Eryne,33783831175,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2003-09-13,France,France,"CONSULTATION BOULOGNE, AGENT DE RESTAURATION, ...",2024-04-24 02:45:09,Oui,NaN,Oui,NaN,Non
4,4,96761|56d8ae051dc42b2c,44431,AMISI,Honorine,33783236753,MANAGER POINT DE VENTE,2- BAR NORD OUEST IN,11:00,FAUX,...,1999-03-17,NaN,NaN,"CONSULTATION BOULOGNE, AGENT DE RESTAURATION, ...",2024-07-08 14:45:13,NaN,Oui,Oui,NaN,NaN

In [5]:
dataset.info()
infos_na = dataset.isna().sum()
print(infos_na)
dataset.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35782 entries, 0 to 35781
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0_x                 35782 non-null  int64
 1   Code                         35782 non-null  object
 2   Matricule                    35782 non-null  object
 3   Nom_x                        35782 non-null  object
 4   Prénom_x                     35782 non-null  object
 5   Téléphone                    35759 non-null  object
 6   Qualification                35781 non-null  object
 7   Equipe                       35777 non-null  object
 8   Heure de convocation         35757 non-null  object
 9   Blacklist                    35782 non-null  object
 10  Passage exterieur            35782 non-null  object
 11  Passage accred               35782 non-null  object
 12  Passage vestiaire            35782 non-null  object
 13  Prise de poste               35782 non-null  object
 14  Fin de poste                 35782 non-null  object
 15  Temps travaillé              35782 non-null  object
 16  Lieu de prise de poste       31601 non-null  object
 17  Lieu de fin de poste         31462 non-null  object
 18  Event                        35782 non-null  object
 19  Unnamed: 0_y                 35782 non-null  int64
 20  Civilité                     35782 non-null  object
 21  Nom_y                        35782 non-null  object
 22  Prénom_y                     35782 non-null  object
 23  Adresse 1                    35782 non-null  object
 24  Code postal                  35782 non-null  object
 25  Ville                        35782 non-null  object
 26  Pays                         35782 non-null  object
 27  Téléphone mobile             35686 non-null  object
 28  Email                        35710 non-null  object
 29  Date naissance               35782 non-null  object
 30  Pays de naissance            35094 non-null  object
 31  Nationalité                  35237 non-null  object
 32  Qualifications               35175 non-null  object
 33  Création                     35782 non-null  object
 34  Formation Stade Prépa BOU    6672 non-null   object
 35  Formation Stade Manager BOU  6115 non-null   object
 36  HACCP BOU                    16422 non-null  object
 37  Langue BOU                   2437 non-null   object
 38  Visite Médicale BOU          7831 non-null   object
dtypes: int64(2), object(37)
memory usage: 10.6+ MB
Unnamed: 0_x                       0
Code                               0
Matricule                          0
Nom_x                              0
Prénom_x                           0
Téléphone                         23
Qualification                      1
Equipe                             5
Heure de convocation              25
Blacklist                          0
Passage exterieur                  0
Passage accred                     0
Passage vestiaire                  0
Prise de poste                     0
Fin de poste                       0
Temps travaillé                    0
Lieu de prise de poste          4181
Lieu de fin de poste            4320
Event                              0
Unnamed: 0_y                       0
Civilité                           0
Nom_y                              0
Prénom_y                           0
Adresse 1                          0
Code postal                        0
Ville                              0
Pays                               0
Téléphone mobile                  96
Email                             72
Date naissance                     0
Pays de naissance                688
Nationalité                      545
Qualifications                   607
Création                           0
Formation Stade Prépa BOU      29110
Formation Stade Manager BOU    29667
HACCP BOU                      19360
Langue BOU                     33345
Visite Médicale BOU            27951
dtype: int64

,Unnamed: 0_x,Code,Matricule,Nom_x,Prénom_x,Téléphone,Qualification,Equipe,Heure de convocation,Blacklist,...,Date naissance,Pays de naissance,Nationalité,Qualifications,Création,Formation Stade Prépa BOU,Formation Stade Manager BOU,HACCP BOU,Langue BOU,Visite Médicale BOU
0,0,82929|a539fb6bb248d168,38859,CISSE,Oumar,33638033860,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2004-12-20,Sénégal,France,"CONSULTATION BOULOGNE, COMMIS DE CUISINE, AGEN...",2023-07-19 02:45:13,Oui,NaN,Oui,NaN,NaN
1,1,83104|1e35386face21ade,38903,HOU,Jerome Wei,33783012177,MANAGER POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2003-09-13,France,France,"CONSULTATION BOULOGNE, MANAGER POINT DE VENTE,...",2023-07-21 02:45:12,NaN,Oui,Oui,NaN,Oui
2,2,84591|d2e6d7cde2df98b8,39423,DRAME,Sokhna,33635502833,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2002-06-29,France,France,"CONSULTATION BOULOGNE, COMMIS DE CUISINE, HOTE...",2023-08-30 02:45:16,Oui,NaN,Oui,NaN,Non
3,3,93097|f39f9bcc50a3ff7f,42702,HALL,Eryne,33783831175,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,...,2003-09-13,France,France,"CONSULTATION BOULOGNE, AGENT DE RESTAURATION, ...",2024-04-24 02:45:09,Oui,NaN,Oui,NaN,Non
4,4,96761|56d8ae051dc42b2c,44431,AMISI,Honorine,33783236753,MANAGER POINT DE VENTE,2- BAR NORD OUEST IN,11:00,FAUX,...,1999-03-17,NaN,NaN,"CONSULTATION BOULOGNE, AGENT DE RESTAURATION, ...",2024-07-08 14:45:13,NaN,Oui,Oui,NaN,NaN

In [6]:
dataset.columns

Index(['Unnamed: 0_x', 'Code', 'Matricule', 'Nom_x', 'Prénom_x', 'Téléphone',
       'Qualification', 'Equipe', 'Heure de convocation', 'Blacklist',
       'Passage exterieur', 'Passage accred', 'Passage vestiaire',
       'Prise de poste', 'Fin de poste', 'Temps travaillé',
       'Lieu de prise de poste', 'Lieu de fin de poste', 'Event',
       'Unnamed: 0_y', 'Civilité', 'Nom_y', 'Prénom_y', 'Adresse 1',
       'Code postal', 'Ville', 'Pays', 'Téléphone mobile', 'Email',
       'Date naissance', 'Pays de naissance', 'Nationalité', 'Qualifications',
       'Création', 'Formation Stade Prépa BOU', 'Formation Stade Manager BOU',
       'HACCP BOU', 'Langue BOU', 'Visite Médicale BOU'],
      dtype='object')

## RGPD
Mise en forme pour fit la RGPD

In [7]:
dataset_RGPD = dataset[[
    "Matricule", "Qualification", "Equipe", 
    "Heure de convocation",
    "Passage exterieur", "Passage accred", "Passage vestiaire", 
    "Prise de poste", "Fin de poste", 
    "Temps travaillé",            
    "Lieu de prise de poste", 
    "Lieu de fin de poste",         
    "Event",
    "Civilité", "Adresse 1", "Code postal", "Ville", "Pays",
    "Date naissance", "Pays de naissance", "Nationalité",
    "Création",
    "Formation Stade Prépa BOU",   
    "Formation Stade Manager BOU", "HACCP BOU", "Langue BOU"
]]

dataset_RGPD.head()

,Matricule,Qualification,Equipe,Heure de convocation,Passage exterieur,Passage accred,Passage vestiaire,Prise de poste,Fin de poste,Temps travaillé,...,Ville,Pays,Date naissance,Pays de naissance,Nationalité,Création,Formation Stade Prépa BOU,Formation Stade Manager BOU,HACCP BOU,Langue BOU
0,38859,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,28-07-2024 11:59:26,0,28-07-2024 12:17:46,28-07-2024 14:32:55,28-07-2024 22:37:41,07:34:46,...,PARIS,France,2004-12-20,Sénégal,France,2023-07-19 02:45:13,Oui,NaN,Oui,NaN
1,38903,MANAGER POINT DE VENTE,2- BAR EST IN,11:00,28-07-2024 11:04:21,0,28-07-2024 11:22:02,28-07-2024 11:36:04,0,0,...,VITRY SUR SEINE,France,2003-09-13,France,France,2023-07-21 02:45:12,NaN,Oui,Oui,NaN
2,39423,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,28-07-2024 10:43:26,0,28-07-2024 10:54:53,0,0,0,...,PARIS,France,2002-06-29,France,France,2023-08-30 02:45:16,Oui,NaN,Oui,NaN
3,42702,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,28-07-2024 10:35:29,0,28-07-2024 10:48:44,0,0,0,...,PIERREFITTE SUR SEINE,France,2003-09-13,France,France,2024-04-24 02:45:09,Oui,NaN,Oui,NaN
4,44431,MANAGER POINT DE VENTE,2- BAR NORD OUEST IN,11:00,28-07-2024 11:10:31,0,28-07-2024 11:20:22,28-07-2024 11:27:47,28-07-2024 22:45:07,10:47:20,...,ATHIS MONS,France,1999-03-17,NaN,NaN,2024-07-08 14:45:13,NaN,Oui,Oui,NaN

## EXPORT
plus qu'a exporter vers un nouveaux csv propore

In [10]:
dataset_RGPD.to_csv("/home/prime/Projets/2026_PROJECT-DA/DATA/dataset.csv")

In [11]:
dataset_RGPD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35782 entries, 0 to 35781
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Matricule                    35782 non-null  object
 1   Qualification                35781 non-null  object
 2   Equipe                       35777 non-null  object
 3   Heure de convocation         35757 non-null  object
 4   Passage exterieur            35782 non-null  object
 5   Passage accred               35782 non-null  object
 6   Passage vestiaire            35782 non-null  object
 7   Prise de poste               35782 non-null  object
 8   Fin de poste                 35782 non-null  object
 9   Temps travaillé              35782 non-null  object
 10  Lieu de prise de poste       31601 non-null  object
 11  Lieu de fin de poste         31462 non-null  object
 12  Event                        35782 non-null  object
 13  Civilité                     35782 non-null  object
 14  Adresse 1                    35782 non-null  object
 15  Code postal                  35782 non-null  object
 16  Ville                        35782 non-null  object
 17  Pays                         35782 non-null  object
 18  Date naissance               35782 non-null  object
 19  Pays de naissance            35094 non-null  object
 20  Nationalité                  35237 non-null  object
 21  Création                     35782 non-null  object
 22  Formation Stade Prépa BOU    6672 non-null   object
 23  Formation Stade Manager BOU  6115 non-null   object
 24  HACCP BOU                    16422 non-null  object
 25  Langue BOU                   2437 non-null   object
dtypes: object(26)
memory usage: 7.1+ MB